### ISSUE TITLE
Doesn't work with Mapped types

### ISSUE THREAD

**Issue by leesiongchan** [whefter/nestjs-joi#1]
```
@ObjectType()
class Person {
  id: string;

  @JoiSchema(Joi.string().required())
  name: string;
}

@InputType()
class PersonInput extends OmitType(Person, ['id'], InputType) {
  @JoiSchema(Joi.string().required())
  hello: string;
}
```

`hello` works, but `name` is not working =(

Ref:
- https://docs.nestjs.com/graphql/mapped-types

**Comment by whefter** [comment]
Hi and thanks for your feedback. The module was not developed with GraphQL in mind and is not tested or documented for use with it, so it's interesting to see it works at least partially.
I'll try and take a look in the next days to see if there's some kind of quick fix, but if it's a major feature extension I'll have to evaluate whether to add support for it.

In the meantime, can you add a full code sample for your case?

**Comment by leesiongchan** [comment]
Ok I will add a simple working project for you to try out. I think the issue here is that mapped-types is not a real inheritance =( I think supporting this might not be straightforward.

**Comment by leesiongchan** [comment]
Add a working example here https://github.com/leesiongchan/nestjs-joi/tree/graphql-example

**Comment by whefter** [comment]
Thanks for the example. It's pretty much like you said: it's not real inheritance in the sense that the prototype chain is not conserved. From a cursory glance it looks like `OmitType` looks at all existing fields on the object to extend in a flat way and then sticks them on a brand new inline abstract class. Lots of things will get lost in that process, among them decorators.

This means the info that `JoiPipe` needs is simply gone by the time it takes a look at the class. One way to solve this would be for the folks over at https://github.com/nestjs/graphql to somehow preserve/re-apply decorator information on properties. 

Failing that, we could think about introducing a new decorator to tell `JoiPipe` about inheritance explicitly, perhaps `@JoiSchemaExtends()`. I'd have to think about that because it looks like that would bring up new questions such as "if both `extends` and `@JoiSchemaExtends()` are specified, how is that handled?`.

**Comment by whefter** [comment]
`@JoiSchemaExtends()` was added in 1.2.0: https://github.com/whefter/nestjs-joi#joischemaextendstype-class-decorator

Thanks again for your example, I took the opportunity to validate some usage scenarios in combination with `@nestjs/graphql` and, after making some fixes, added some general usage notes: https://github.com/whefter/nestjs-joi#a-note-on-nestjsgraphql
