### ISSUE TITLE
Add Support for enum

### ISSUE THREAD

**Issue by atul161** [whefter/nestjs-joi#11]

**Comment by whefter** [comment]
Could you provide some more information on this?

**Comment by atul161** [comment]
Hii @whefter ,

I don't find any predefined function for validating enum variables. ie: How can i validate the value of variable matches with the value inside enum.

**Comment by whefter** [comment]
Since JS has no native enum type, there can't be any "type" validation. This question is related more to Joi and possibly TypeScript. Possibly something like this would work (it's how I validate enums)?
````typescript
enum MyVal {
  Foo = 'Foo',
  Bar= 'Bar',
}
...
const enumSchema = Joi.string().valid(...Object.values(MyVal));
```
Please refer to the Joi and/or TypeScript documentations. As far as I can see, not a direct issue with this module, so closing. Feel free to reopen if I've misunderstood the issue.
