### ISSUE TITLE
Response validation

### ISSUE THREAD

**Issue by redwert** [whefter/nestjs-joi#6]
Is there an ability to validate a response schema?

  ```
@Post()
  @ApiOperation({ description: 'Create something })
  @ApiResponse({ status: HttpStatus.OK, description: 'Success response', type: CreateSomethingResponseDto })
  async create(
    @Body() body: CreateSomethingDto,
  ): Promise<Something> {
    return this.somethingService.create(body)
  }
```
  
  And CreateSomethingResponseDto:
```
  import { JoiSchema, JoiSchemaOptions } from 'nestjs-joi'
  
  @JoiSchemaOptions({stripUnknown: true})
export class CreateSomethingResponseDto {
  @JoiSchema(integerRequired)
  @ApiProperty({ example: 1, description: 'Tenant id', nullable: true })
  id: number | null
} 
```

**Comment by whefter** [comment]
Not at the moment, but it's an interesting idea. `@ApiResponse()` is part of the Swagger package - meaning it would only work with that package - and does not offer any hooks that could be used for this, as far as I know. Simply put, the concept of `Pipes` in NestJS is made specifically for input data, so it's easy to do something like this for input data, as opposed to output data.

As for response validation, probably the most straightforward way to implement it would be to use interceptors (https://docs.nestjs.com/interceptors), **but** we have no way of knowing the `type` class of the response, so it would have to be specified manually, perhaps with a decorator. Also, this would not work if a route uses the `@Res()` decorator.

I'll keep this in mind and think about it a bit. If you know of a way to get the response type for the route from the `ExecutionContext` or similar, let me know, though I think this will be difficults, since a lot of the time the actual type will have to be unpacked from a `Promise<>` or similar, so the decorator would probably be the easiest way...

**Comment by redwert** [comment]
After some investigation, I found how to get type passed to ApiResponse.

It is just a quick test, so it is not ideal. Here is a short example of how to get it:

test.dto.ts
```
export class TestDto{
  superString: string
}
```

response.interceptor.ts
```
import { tap } from 'rxjs/operators';
import {Reflector} from "@nestjs/core";
import {DECORATORS} from "@nestjs/swagger/dist/constants";

@Injectable()
export class ResponseInterceptor implements NestInterceptor {
  constructor(private reflector: Reflector) {}

  intercept(context: ExecutionContext, next: CallHandler): Observable<any> {
    return next
      .handle()
      .pipe(
        tap(() => {
          const swaggerData = this.reflector.get<string[]>(DECORATORS.API_RESPONSE, context.getHandler());
          console.log(swaggerData['200'].type)
        }),
      );
  }
}
```

in main.ts
```
app.useGlobalInterceptors(new ResponseInterceptor(new Reflector()));
```

in some.controller.ts
```
@Get()
  @ApiResponse({status: 200, type: TestDto})
  getHello(): string {
    return 'Hello world';
  }
```

and console output:
```
[class TestDto]
```

I didn't investigate the next steps for applying validation.
Is it helpful information?

**Comment by whefter** [comment]
Thanks for investigating!

Your example relies on an internal constant of the `@nestjs/swagger` module (the `@nestjs/swagger/dist/constants` import), which could technically change at any time, so I don't think it's safe to use.
Like I said above, this would also introduce a hard dependency on the `@nestjs/swagger` module, which otherwise has no connection to the purpose of this module.

Should this be implemented, I believe the best route would be a custom decorator on the route to explicitly specify the return type, and then only routes with that decorator would have their response validated.

I'm not sure this has broad use, though. Unlike the input, the output has fairly strong validation already given that we're using TypeScript, provided you are using types consistently.
Can you give an example of your use case that would benefit from such strong response validation when compared to stringent use of TypeScript types?

**Comment by whefter** [comment]
Closing as stale. @redwert feel free to reopen if you have any additions.
